---
name: "pipeline-components-black"
description: "black by Pipeline Components"
author: "Robbert Müller <spam.me@grols.ch>"
branding:
  icon: "flag"
  color: "green"
inputs:
  directory:
    description: "Directory to lint"
    required: false
    default: .
  options:
    description: "Additional options"
    required: false
    default: "--fast --check --verbose"
runs:
  using: "docker"
  image: docker://pipelinecomponents/black
  args:
    - black
    - "${{ inputs.options }}"
    - "--"
    - "${{ inputs.directory }}"
